### ISSUE TITLE
Richer intrinsics support

### ISSUE THREAD

**Issue by JustasMasiulis** [JustasMasiulis/xorstr#10]
Currently there only is support for SSE and AVX256 so we only support one architecture and are not using the latest and greatest intrins like AVX512

**Comment by kotori2** [comment]
also it kills ARM support... ARM doesn't have things like AVX/SSE

**Comment by JustasMasiulis** [comment]
Personally I don't really have plans to implement ARM support, but if enough people want it - I'll work on it

**Comment by JustasMasiulis** [comment]
ARM support added; because of necessity to inline _everything_ by hand I won't be adding any more intrinsics unless people specifically ask for them by opening an issue.
