### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by coofcookie** [JustasMasiulis/xorstr#15]
![image](https://user-images.githubusercontent.com/42417026/47809053-39abb580-dd40-11e8-96f1-7e114faa5c16.png)
After update, I have this error for every xorstr. Can you help me?

**Comment by JustasMasiulis** [comment]
Could you provide the compiler output?
Because this looks like an intellisense error and they aren't always accurate.

**Comment by coofcookie** [comment]
OK, please wait 2 minutes :)

**Comment by coofcookie** [comment]
![image](https://user-images.githubusercontent.com/42417026/47815009-759a4700-dd4f-11e8-97b1-3428d6fc5d04.png)

![image](https://user-images.githubusercontent.com/42417026/47815032-82b73600-dd4f-11e8-89e3-2fd826606ae1.png)

**Comment by coofcookie** [comment]
![image](https://user-images.githubusercontent.com/42417026/47815136-c7db6800-dd4f-11e8-9b4e-b487c1da326e.png)
and here is compiler output

**Comment by JustasMasiulis** [comment]
@coofcookie I only see 2 errors and they don't really seem to be related to xorstr library.

To fix the first one add _CRT_SECURE_NO_WARNINGS to the preprocessor definitions in solution settings.

As for the second one I don't really know. It says it cannot find `__crv` but I don't really remember anything named like that being in the library.

You can ignore all errors that don't come from the compiler output window (the last picture you sent)

I can't really help you with anything more unless the `__crv` stuff somehow comes from my code.

**Comment by coofcookie** [comment]
A already have _CRT_SECURE_NO_WARNINGS is definitions :)

**Comment by JustasMasiulis** [comment]
yes, sorry - it was a warning. I mistook it for an error.

Did you figure out the `__crv` stuff?

**Comment by coofcookie** [comment]
No. I really do not know what to do now. Do you know and other xorstr? I try to use older versions of your xorstr, I can build it, but it is crashing. I saw you fix the crashing issue in latest update and I can not use it because I can not build it.

**Comment by JustasMasiulis** [comment]
what's the exception? Try defining JM_XORSTR_DISABLE_AVX_INTRINSICS

Also from quick google search the `__crv` stuff seems to come from https://github.com/fritzone/obfy

**Comment by coofcookie** [comment]
yes, this is the cvr stuff

**Comment by coofcookie** [comment]
I tried 1 version older xorstr now with the "JM_XORSTR_DISABLE_AVX_INTRINSICS" and it is working good! Thanks!

**Comment by JustasMasiulis** [comment]
Well that's a bit strange, but issue is solved I guess 👍
