### ISSUE TITLE
Compiler Error when giving char* or wchar as parameter

### ISSUE THREAD

**Issue by MagicTripz** [JustasMasiulis/xorstr#16]
Great Project, i first used it when the 100 char limit still existed, now you updated it and i have an error that says smth like: no instance of the function template" ::jm::make_xorstr" fits the argument list.
got visualstudios in german so i dont know the exact english translation, but yea worked before with that 100 char limit, idk why it does not work now. Only thing i did was defining disable avx

**Comment by JustasMasiulis** [comment]
Might have possibly fixed your issue on this version. Can you check on it?

**Comment by MagicTripz** [comment]
Sadly it didnt solve the problem ill attach a screen so you know what i mean eventhough its not your language
![xorstrprobleme](https://user-images.githubusercontent.com/33939728/49597716-5198d980-f97d-11e8-886a-6831964c80be.JPG)

**Comment by JustasMasiulis** [comment]
That's just intellisense. Are you sure it's actually an error when compiling? If it is, a screenshot of the output window would be the most useful - it gives the most accurate error information.

**Comment by MagicTripz** [comment]
aleks-s commit fixed it

**Comment by JustasMasiulis** [comment]
That's great. I'll close the issue now
