### ISSUE TITLE
There are some problems with compiling code!

### ISSUE THREAD

**Issue by X-Crack** [JustasMasiulis/xorstr#19]
I use c++ 17.

VS2017 15.9.3

C++ 17 is hard to compile!

And hope to eliminate warnings, do not use macros.

It is better to be able to import various structures like standard libraries.

**Comment by JustasMasiulis** [comment]
> C++ 17 is hard to compile!

What do you mean by saying that?

> And hope to eliminate warnings, do not use macros.

Macros are necessary unless you are using compiler that supports:
- c++20
- extension for user defined templated string literals (clang or gcc)

> It is better to be able to import various structures like standard libraries.

I do not really understand what you want to tell me with this.

**Comment by JustasMasiulis** [comment]
Well I'll be closing this issue now as it's not getting anywhere
