### ISSUE TITLE
Latest MSVC template "auto is not allowed here"

### ISSUE THREAD

**Issue by moshater** [JustasMasiulis/xorstr#21]
`template<auto... Cs>`

MSVC complain about it.

**Comment by JustasMasiulis** [comment]
Have you changed language standard to c++17?

**Comment by moshater** [comment]
My bad, forget to check the setting. It's working now.

**Comment by timoxa5651** [comment]
having same issue, but i have already set C++17 option...
![image](https://user-images.githubusercontent.com/41595975/73139766-64d79e80-4082-11ea-80ee-dd034ff588fa.png)
![image](https://user-images.githubusercontent.com/41595975/73139770-7caf2280-4082-11ea-85db-3479aef2b049.png)

**Comment by JustasMasiulis** [comment]
> having same issue, but i have already set C++17 option...
> ![image](https://user-images.githubusercontent.com/41595975/73139766-64d79e80-4082-11ea-80ee-dd034ff588fa.png)
> ![image](https://user-images.githubusercontent.com/41595975/73139770-7caf2280-4082-11ea-85db-3479aef2b049.png)

What's the compiler output

**Comment by Anton-V-K** [comment]
Any chances the header may be successfully processed by a C++14 compiler (VS2015)?
I was going to try it in an old project (which is built with vc140 toolset), but your classes use C++17 features (like `auto` in template parameters).

**Comment by JustasMasiulis** [comment]
@Anton-V-K 

I could probably port it to c++14 or maybe even 11 l. I'll take a look tomorrow.

**Comment by JustasMasiulis** [comment]
@Anton-V-K Making it c++14 would require a bit too much work at the moment.

What I was able to fix or know that fixing isn't hard
- `auto` with non type template parameters: easy fix by adding parameter for the char type separately
- fold expressions: easy fix by expanding the parameter pack into fake function. Adds some overhead in debug builds.

What is harder to fix and I don't want to touch though is the technique of using lambda to populate variadic template of chars from a string literal. All the other approaches that I remember/had used in the past are really ugly and usually generate tons of intermediary templates.

**Comment by Anton-V-K** [comment]
@JustasMasiulis , thanks for looking into this.
It's a pity the code can't be compiled in the c++14 mode.
