### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by jaspergould** [JustasMasiulis/xorstr#22]
Code

```
#include <iostream>
#include "xorstr_strings.hpp"

int main()
{
	printf(xorstr("hello world!!!***").crypt_get());
}
```

AMD FX 8370, VS19, v142 toolset

http://prntscr.com/n8w4wl

**Comment by jaspergould** [comment]
same problem

`xorstr_(";?-!!<|+^-;%}=#>")`

**Comment by JustasMasiulis** [comment]
defining `JM_XORSTR_DISABLE_AVX_INTRINSICS` should solve your issue
