### ISSUE TITLE
Crash on Windows Server

### ISSUE THREAD

**Issue by Mecanik** [JustasMasiulis/xorstr#23]
Hi, 

I just tested on WS 2016 Essentials x64 and my app crashes with undefined behavior.

Not sure as why, I was using VS 2017 and x64 Release mode. 

Maybe worth checking when you have time ?

**Comment by JustasMasiulis** [comment]
Perhaps AVX intrinsics are not supported? Try defining JM_XORSTR_DISABLE_AVX_INTRINSICS

**Comment by Mecanik** [comment]
Thank you, JM_XORSTR_DISABLE_AVX_INTRINSICS fixed my problem.
