### ISSUE TITLE
Incorrect string in gcc release mode

### ISSUE THREAD

**Issue by BullyWiiPlaza** [JustasMasiulis/xorstr#26]
With optimizations enabled using `gcc` version `9.2.1` (`-O3` flag) on `Ubuntu` the following code produces an incorrect output:

```
#include <iostream>
#include "xorstr.hpp"

int main() {
	const auto decrypted_string = xorstr_("Hello, world!");
	std::cout << decrypted_string << std::endl;

	return EXIT_SUCCESS;
}
```

Output:
`�	a6�2F���!%��E�E���`

Decompiled:
![image](https://user-images.githubusercontent.com/7620135/74267941-466ed580-4d07-11ea-828d-15c31e38a432.png)

In debug mode the code correctly outputs:
`Hello, world!`

Decompiled:
![image](https://user-images.githubusercontent.com/7620135/74267897-32c36f00-4d07-11ea-8fe8-45559b6dac6d.png)

---

Interestingly, in `MSVC` it works fine either way.

Decompiled debug build:
![image](https://user-images.githubusercontent.com/7620135/74269006-1a545400-4d09-11ea-8cd1-f3e3c420d3ef.png)

Decompiled release build:
![image](https://user-images.githubusercontent.com/7620135/74269085-3c4dd680-4d09-11ea-9d1b-6d5badd181a1.png)

**Comment by JustasMasiulis** [comment]
you are printing a dangling pointer

**Comment by BullyWiiPlaza** [comment]
@JustasMasiulis Ah. So inlining the variable fixes it?

```
int main() {
	std::cout << xorstr_("Hello, world!") << std::endl;
	return EXIT_SUCCESS;
}
```

Now it works correctly. Damn. This is dangerous to accidentally mess up.

**Comment by JustasMasiulis** [comment]
yeah, that would be how you would most commonly use it, although it's entirely possible to store it and use it multiple times
```cpp
auto xs = xorstr("something);
puts(xs.crypt_get());
puts(xs.get());
```
