### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by debugger** [JustasMasiulis/xorstr#3]
On one of my RDPs I got this:
![image](https://user-images.githubusercontent.com/22308297/43157504-d6e8b4b6-8f42-11e8-9e49-7504c4486b55.png)

**Comment by Nou4r** [comment]
Strange i just recently also had the same issue

**Comment by debugger** [comment]
Yep, that was the issue. Thanks 👍

**Comment by Randshot** [comment]
How did he even compile the program without enabling the necessary ABI?
I had to explicitly enable it via flags when compiling with GCC/Clang.
