### ISSUE TITLE
incorrect string

### ISSUE THREAD

**Issue by AlexandeRSaxoN7** [JustasMasiulis/xorstr#30]
![image](https://user-images.githubusercontent.com/64085106/85926759-459ba200-b8aa-11ea-85b8-ef52cd2672d1.png)
![image](https://user-images.githubusercontent.com/64085106/85926762-4cc2b000-b8aa-11ea-8cba-8c9fbd51522c.png)

**Comment by AlexandeRSaxoN7** [comment]
I think that str1 is a dangling pointer. I have only one question: why the same code works fine with std::string (...).c_str()?

**Comment by JustasMasiulis** [comment]
> I think that str1 is a dangling pointer. 

Yep. That's the problem you have.

> I have only one question: why the same code works fine with std::string (...).c_str()?

🤷 just lucky I guess, because it shouldn't and most likely if you just add some more stuff it will instantly break.
