### ISSUE TITLE
IntelliSense error

### ISSUE THREAD

**Issue by playday3008** [JustasMasiulis/xorstr#35]
Error code: E0146
![image](https://user-images.githubusercontent.com/18056374/99377335-fd633780-28bd-11eb-8892-987d3165f638.png)

without #define
![image](https://user-images.githubusercontent.com/18056374/99377552-40bda600-28be-11eb-8087-fcdb137cb2a6.png)

Using: Latest Visual Studio 2019
Project settings:
![image](https://user-images.githubusercontent.com/18056374/99377689-69de3680-28be-11eb-852d-eb2e71fac362.png)

**Comment by scizzydo** [comment]
After upgrading from 16.8.2 on visual studio 2019 from 16.8.1 I am also experiencing this same issue.

**Comment by JustasMasiulis** [comment]
This fixed it for me on latest VS preview version. If it's still there for you feel free to reopen the issue
