### ISSUE TITLE
windows7 x64 bug

### ISSUE THREAD

**Issue by liwei1024** [JustasMasiulis/xorstr#37]
Encrypting strings longer than 15 characters in Windows 7 will crash

int main(int argc, char* argv[])
{
	//15 normal
	printf("%s\n", xorstr_("000000000000000"));
	//16 crash
	printf("%s\n", xorstr_("1111111111111111"));

	system("pause");

	return 0;
}

**Comment by SpriteOvO** [comment]
Maybe because ur CPU doesn't support AVX instruction. Did u try to define `JM_XORSTR_DISABLE_AVX_INTRINSICS` macro?

**Comment by liwei1024** [comment]
我靠 回复那么快

**Comment by liwei1024** [comment]
> Maybe because ur CPU doesn't support AVX instruction. Did u try to define `JM_XORSTR_DISABLE_AVX_INTRINSICS` macro?
