### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by mq1n** [JustasMasiulis/xorstr#4]
hello, there are have some compile problems with long strings and/or special chars, e.g;

> **printf(xorstr("There has to be an exception throw on InitLogger (spdlog::spdlog_ex)\n").crypt_get());** 

Error (active)	E0135	class "jm::detail::string_builder<char, jm::detail::tstring_<char>, 'T', 'h', 'e', 'r', 'e', ' ', 'h', 'a', 's', ' ', 't', 'o', ' ', 'b', 'e', ' ', 'a', 'n', ' ', 'e', 'x', 'c', 'e', 'p', 't', 'i', 'o', 'n', ' ', 't', 'h', 'r', 'o', 'w', ' ', 'o', 'n', ' ', 'I', 'n', 'i', 't', 'L', 'o', 'g', 'g', 'e', 'r', ' ', '(', 's', 'p', 'd', 'l', 'o', 'g', ':', ':', 's', 'p', 'd', 'l', 'o', 'g', '_', 'e', 'x', ')', '\n', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000'>" has no member "type"	ConsoleApplication1	C:\Users\Koray\Desktop\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp	12	

> **printf(xorstr("SELECT * FROM __InstanceCreationEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process'").crypt_get());**

Error (active)	E0135	class "jm::detail::string_builder<char, jm::detail::tstring_<char>, 'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', '_', '_', 'I', 'n', 's', 't', 'a', 'n', 'c', 'e', 'C', 'r', 'e', 'a', 't', 'i', 'o', 'n', 'E', 'v', 'e', 'n', 't', ' ', 'W', 'I', 'T', 'H', 'I', 'N', ' ', '1', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'T', 'a', 'r', 'g', 'e', 't', 'I', 'n', 's', 't', 'a', 'n', 'c', 'e', ' ', 'I', 'S', 'A', ' ', '\'', 'W', 'i', 'n', '3', '2', '_', 'P', 'r', 'o', 'c', 'e', 's', 's', '\'', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000', '\000'>" has no member "type"	ConsoleApplication1	C:\Users\Koray\Desktop\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp	12	

IDE: Visual studio 2017(17134 SDK toolset)

**Comment by JustasMasiulis** [comment]
Will look into this

**Comment by JustasMasiulis** [comment]
I am able to compile these examples without any problems.
I think you may have mistaken the intellisense errors with actual compiler errors.

In the library there currently is a hard limit of 99 characters IIRC so I may raise that if needed, but you don't seem to be hitting it yet.

Concerning special chars there was a bug with encoding extended ASCII characters that should have been fixed some time ago.

**Comment by mq1n** [comment]
Yes, looks like it's a intellisense problem the code successfully compiled and running but I don't get it why it happens as error.

**Comment by JustasMasiulis** [comment]
Eh. Intellisense is sketchy rather often. I guess I can close this now?
