### ISSUE TITLE
Visual Studio 2017    15.9.35    err !!!!!!!!

### ISSUE THREAD

**Issue by c3358** [JustasMasiulis/xorstr#40]
![4](https://user-images.githubusercontent.com/23057656/115988355-e69eda80-a5eb-11eb-9718-0da8996e382d.jpg)

![1](https://user-images.githubusercontent.com/23057656/115988363-ebfc2500-a5eb-11eb-805d-2b7e6a82eb31.jpg)

![2](https://user-images.githubusercontent.com/23057656/115988367-f1596f80-a5eb-11eb-9ac6-184a509f87e4.jpg)

![3](https://user-images.githubusercontent.com/23057656/115988368-f61e2380-a5eb-11eb-98d9-2ac3eddf9b3f.jpg)

**Comment by c3358** [comment]
test code:

std::puts(  xorstr_("an extra long hello_world")  );

**Comment by c3358** [comment]
![1](https://user-images.githubusercontent.com/23057656/115988723-988ad680-a5ed-11eb-91ad-33d13a5a3aee.jpg)

![2](https://user-images.githubusercontent.com/23057656/115988725-9b85c700-a5ed-11eb-8bca-0392dd05a58d.jpg)

**Comment by JustasMasiulis** [comment]
Visual Studio 2017 not supported - #34 

Use commit [b37d4de](https://github.com/JustasMasiulis/xorstr/commit/b37d4de9094fc4ef065cb8fbe70be062c0532618)
