### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MCAki06** [JustasMasiulis/xorstr#41]
These are all the errors for me:

- parameter pack "Keys" was referenced but not expanded Line: 139	
- parameter pack "Keys" was referenced but not expanded Line: 182
- argument list for class template "jm::xor_string" is missing Line: 208
- expected a ')' Line: 208
- expected a ';' Line: 208

Somebody can help me please?

**Comment by JustasMasiulis** [comment]
What compiler did you use?

**Comment by MCAki06** [comment]
I'm using Visual Studio 2019

**Line 139**
`alignas(alignment) std::uint64_t keys[]{ JM_XORSTR_LOAD_FROM_REG(Keys)... };`

**Line 182**
`alignas(alignment) std::uint64_t keys[]{ JM_XORSTR_LOAD_FROM_REG(Keys)... };`

**Line 208 (3 errors here)**
`    xor_string(L l, std::integral_constant<std::size_t, Size>, std::index_sequence<Indices...>) -> xor_string<
            std::remove_const_t<std::remove_reference_t<decltype(l()[0])>>,
            Size,
            std::integer_sequence<std::uint64_t, detail::key8<Indices>()...>,
            std::index_sequence<Indices...>>;`

**Comment by JustasMasiulis** [comment]
VS 2019 is supposed to work I think. Did you enable c++17 or c++latest?

 Did a quick test on godbolt and didn't seem like there are problems, so it would be really nice if you could provide a minimal reproduction / what the code that causes this looks like.

**Comment by MCAki06** [comment]
Well, now I set it to C++ latest, and most of the errors are gone only just the `'parameter pack "Keys" was referenced but not expanded'` still here.

**Comment by JustasMasiulis** [comment]
Yeah. That doesn't really tell much. I need a small example of how you cause this.

**Comment by JustasMasiulis** [comment]
For me on VS 2019 Preview everything seems to compile fine.

```cpp
    std::cout << xorstr_("test") << xorstr_("long test for AVX intrinsics to trigger");
    std::wcout << xorstr_(L"wide test") << xorstr_("wide and long test for AVX intrinsics to trigger");
```

**Comment by MCAki06** [comment]
> Yeah. That doesn't really tell much. I need a small example of how you cause this.

![image](https://user-images.githubusercontent.com/58387441/120501814-337f8900-c3c2-11eb-8d82-139573697908.png)
bruh

**Comment by MCAki06** [comment]
I mean i'm getting this but i don't know why whilst I'm using c++17

**Comment by JustasMasiulis** [comment]
Once again. This does not tell anything.

First of all that is the errors windows in Visual Studio. They could mean _literally_ nothing and be caused by another problem in your code, or even not exist at all if it's an error only intellisense sees. If you want errors that help - look at the `output` window instead.

I have been telling you that I need a minimal repro. I can't fix this if you just show me the errors without showing the code.

**Comment by MCAki06** [comment]
Well, now it's working. VS just needed a restart 😂
