### ISSUE TITLE
Bug of pointer's memory occupied

### ISSUE THREAD

**Issue by lanyeeee** [JustasMasiulis/xorstr#42]
the bug will appear if you choose to compile with x64 instead x86
![image](https://user-images.githubusercontent.com/73207840/124356485-cbce8f00-dc48-11eb-8d3b-5ce067d41fa5.png)
![image](https://user-images.githubusercontent.com/73207840/124356408-798d6e00-dc48-11eb-9a6c-7b1e143a7150.png)
because 1 pointer take 4 bytes in x86, take 8 bytes in x64

So if I want to compile with x64, I have to do like this way
![image](https://user-images.githubusercontent.com/73207840/124356628-8ced0900-dc49-11eb-9d2d-99026f2eafb8.png)
"unsigned long long" take 8 bytes,same as the pointer

**Comment by JustasMasiulis** [comment]
Sorry, but how is this related to my `xorstr` library?

I think you might want to open the issue in https://github.com/btwael/SuperString and not here?

**Comment by lanyeeee** [comment]
It's embarrassing. It's in the wrong place. I'm sorry

**Comment by JustasMasiulis** [comment]
> It's embarrassing. It's in the wrong place. I'm sorry

No problem. Mistakes happen.
