### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by GamotronicYT** [JustasMasiulis/xorstr#44]
How can i fix it :( ??? 
![vs20198support](https://user-images.githubusercontent.com/79149622/132237238-7d1b9396-afb6-4bb2-8d1e-5bc30e67e013.PNG)

**Comment by JustasMasiulis** [comment]
Can you copy me the output window contents related to this error?

**Comment by GamotronicYT** [comment]
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur (active)	E0018	')' attendu	EraV2	C:\Users\Gamotronic\Desktop\TF uitile folder\EraV2-master\xorstr.hpp	208	
Erreur (active)	E0065	';' attendu	EraV2	C:\Users\Gamotronic\Desktop\TF uitile folder\EraV2-master\xorstr.hpp	208	
Erreur (active)	E0441	liste d'arguments de modèle de classe "jm::xor_string" manquante	EraV2 C:\Users\Gamotronic\Desktop\TF uitile folder\EraV2-master\xorstr.hpp	208	


> Can you copy me the output window contents related to this error?

**Comment by GamotronicYT** [comment]
![Uploading capturen100000.PNG…]()

**Comment by GamotronicYT** [comment]
![Uploading capturen100000.PNG…]()

**Comment by GamotronicYT** [comment]
**And the capture :** 
![capturen100000](https://user-images.githubusercontent.com/79149622/132239149-72da202c-a63f-4ad5-9597-8e3dd513a3aa.PNG)

**Comment by JustasMasiulis** [comment]
Do you have C++17 enabled? VS 2019 should work perfectly fine.

**Comment by GamotronicYT** [comment]
where I can see if C++17 is enabled ??

> Do you have C++17 enabled (The default is still C++14 IIRC)? VS 2019 should work perfectly fine.

**Comment by GamotronicYT** [comment]
**this ??? **
![capture 100001](https://user-images.githubusercontent.com/79149622/132239925-65b8b473-2fba-43dc-9699-9fc5241e4a30.PNG)

**Comment by JustasMasiulis** [comment]
Yes. Set it to 17 or latest

**Comment by GamotronicYT** [comment]
like this ?? 
![capture 100002](https://user-images.githubusercontent.com/79149622/132240660-dce4ec61-4573-4a73-b7b4-a5215b2a8014.PNG)


> Yes. Set it to 17 or latest (don't forget to set this on all configurations and not only your active one)

**Comment by GamotronicYT** [comment]
**this not work :/**
![hmmmno](https://user-images.githubusercontent.com/79149622/132241371-608e7bdc-5bcb-4c3f-a776-13a5de82a5e9.PNG)

**Comment by GamotronicYT** [comment]
**this work !!!!!!**
![thankkkyouuu](https://user-images.githubusercontent.com/79149622/132241598-32fd7ca3-c900-4d77-b290-6f9c3e0ff215.PNG)
**thank you sooooo muuuuchhhhhh** 😄
