### ISSUE TITLE
Runtime Exceptions with old-gen Intel Processors

### ISSUE THREAD

**Issue by nal532** [JustasMasiulis/xorstr#52]
Hey there,

Everything compiles and runs properly on my Intel i7-9700k, 99% of my userbase also experienced no issues running my application. Issues came up for users on old-gen Intel processors where exceptions were thrown before the application was even loaded into memory. After some troubleshooting, I downgraded to a November 2020 version of the repository, and the issues were resolved. I'm not sure what caused this as I wasn't able to properly debug it as the issue wasn't occurring on my end.

Compiled with MSVC v143 on C++20

The following are the CPUs users were using who couldn't run with the latest version of xorstring:
Intel(R) Xeon(R) X5660
Intel(R) Core i7-2600
Intel(R) Core i5-3330

If you need more info, let me know.

**Comment by JustasMasiulis** [comment]
`#define JM_XORSTR_DISABLE_AVX_INTRINSICS`

**Comment by nal532** [comment]
> `#define JM_XORSTR_DISABLE_AVX_INTRINSICS`

Duh! Thank you :)
