### ISSUE TITLE
xorstr_ CPU Issues

### ISSUE THREAD

**Issue by xo1337** [JustasMasiulis/xorstr#53]
I've done some testing and xorstr_ does not work on certain types of CPU's such as the Intel I5 2500 model. I've yet to find the reason why it crashes.

**Comment by xo1337** [comment]
I apologize, I have fully read your github repo and I fixed the issue now :)

**Comment by JustasMasiulis** [comment]
Yeah. this is a somewhat common issue. Having AVX2 on by default might not have been the best choice, but as detailed in readme it's a single define to disable it.
