### ISSUE TITLE
Error: argument list for class template "jm::xor_string" is missing

### ISSUE THREAD

**Issue by AlQaida** [JustasMasiulis/xorstr#54]
Sup, im quite new to c++ and coding overall so my question might be retarded who knows. 
Ive while trying to use xorstr ran into this error: 
![image](https://user-images.githubusercontent.com/80467438/163673275-172547b8-9a68-43cf-8233-6996f82c427d.png)
I checked the source from a project i was staff on about a year ago and when i open that project it works fine, no errors, nothing.

**Comment by JustasMasiulis** [comment]
Hey, you closed the issue instantly so I'm not sure if you got it solved or not.

Either way make sure you set your C++ standard to C++17 or later. Otherwise give me the error from the `output` window.
