### ISSUE TITLE
C2975

### ISSUE THREAD

**Issue by batininhani** [JustasMasiulis/xorstr#55]
'_Val': invalid template argument for 'std::integral_constant', expected compile-time constant expression (compiling source file main.cpp) utils\security\xorstr.h 122

**Comment by JustasMasiulis** [comment]
What are you compiling this with? What are your settings? Can you show me the full output window and possibly the user code that causes this error?

**Comment by batininhani** [comment]
Had an wrong expression that I didn't notice, solved.

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________
