### ISSUE TITLE
Support x86/x86_64 for Android emulator

### ISSUE THREAD

**Issue by ghost** [JustasMasiulis/xorstr#56]
The app crashes when using xorstr without avx support on x86 lib for Android emulator. Can you add x86/x86_64 support for Android platform?
![image](https://user-images.githubusercontent.com/70694330/197771161-732bb309-208b-40e2-a381-ed18944ad4b9.png)

**Comment by ghost** [comment]
x86 support would be nice because i'm adding x86 support for emulator compatibilty. I wonder what instruction Android is using

Here is CPU info (Ignore CPU cores because I configured like that)

64-bit
![image](https://user-images.githubusercontent.com/111238729/198307355-e2b6691b-38ed-49ae-9cf4-ad6d6bba8741.png)

32-bit
![image](https://user-images.githubusercontent.com/111238729/198307613-1567291e-2241-499a-a8fe-28d5ae508324.png)

**Comment by JustasMasiulis** [comment]
Hey, so what exact instruction is it crashing on?

Currently when AVX support is disabled, SSE2 instructions are used (`pxor`, `movdqa`).

If SSE2 is no-go, but SSE is OK, it should be pretty trivial to change this piece of code:
```
        ((Indices >= sizeof(_storage) / 16 ? static_cast<void>(0) : _mm_store_si128(
            reinterpret_cast<__m128i*>(_storage) + Indices,
            _mm_xor_si128(_mm_load_si128(reinterpret_cast<const __m128i*>(_storage) + Indices),
                          _mm_load_si128(reinterpret_cast<const __m128i*>(keys) + Indices)))), ...);
```
to use `_mm_store_ps`, `_mm_load_ps` and `_mm_xor_ps`, which should be functionally equivalent, but use the `__m128` type instead (packed floats instead of integers) and only require SSE.

**Comment by JustasMasiulis** [comment]
> Here is CPU info (Ignore CPU cores because I configured like that)

Assuming it supported everything a Silvermont generation CPU should, SSE and SSE2 shouldn't cause any problems. Are you sure that AVX was for sure disabled?

**Comment by ghost** [comment]
Nevermind, it was an issue with `const char* const`, I implemented it other way to make it work. Xorstr works perfectly fine on both x86 and x86_64 emulators

@BoomboomDada Emulator using fake CPU info, so the info in AIDA64 are not accurate. Use `cat /proc/cpuinfo` in terminal.

![image](https://user-images.githubusercontent.com/70694330/198837721-e5a7134b-1402-42a7-b76e-76e78c6657ab.png)

Emulator using CPU passthrough so it supports AVX directly but the compiler doesn't support AVX, therefore `#define JM_XORSTR_DISABLE_AVX_INTRINSICS` is mandatory
