### ISSUE TITLE
C++ requires a type specifier for all declaration

### ISSUE THREAD

**Issue by ghost** [JustasMasiulis/xorstr#57]
Jut got an error "C++ requires a type specifier for all declaration", and I have no idea what is wrong. How do I fix it?

![image](https://user-images.githubusercontent.com/111238729/208760663-eba7137c-4af4-4af5-89f1-43200942ce8d.png)

**Comment by JustasMasiulis** [comment]
Is your project configured for C++17?

**Comment by ghost** [comment]
Yes

**Comment by JustasMasiulis** [comment]
If it's an actual error and not just a red squiggle, can you post the compiler output?

**Comment by ghost** [comment]
It's an actual error. Nevermind, I didn't saw there was another cmake files, so I added C++17 flag for it too
