### ISSUE TITLE
weird crashing on long strings

### ISSUE THREAD

**Issue by hessfire** [JustasMasiulis/xorstr#61]
executing this code (on both x86 and x64 arch) crashes on third line

MessageBoxA(0, xorstr("test"), 0, 0);
MessageBoxA(0, xorstr("longertest"), 0, 0);
MessageBoxA(0, xorstr("muchlongertest!!!"), 0, 0);
	
test and longertest displays normally but when it comes to display 'muchlongertest!!!' i get crashed with following reason:

![r](https://github.com/JustasMasiulis/xorstr/assets/134144364/38d38ea9-09f8-4da6-9342-aeb11f3b111c)

**Comment by JustasMasiulis** [comment]
`#define JM_XORSTR_DISABLE_AVX_INTRINSICS`

**Comment by hessfire** [comment]
> `#define JM_XORSTR_DISABLE_AVX_INTRINSICS`

already tried, still same

**Comment by JustasMasiulis** [comment]
Please open the disassembly view and show the instruction that's invalid then. You can also post the code you use if it's something small

**Comment by hessfire** [comment]
> Please open the disassembly view and show the instruction that's invalid then. You can also post the code you use if it's something small

![disaster_1](https://github.com/JustasMasiulis/xorstr/assets/134144364/b62f9a3e-79f1-4ec7-abc0-467fe001b5a5)
![disaster_2](https://github.com/JustasMasiulis/xorstr/assets/134144364/44c737c9-9cea-4901-a028-6ba8d5d3b3b7)

**Comment by hessfire** [comment]
adding `#define JM_XORSTR_DISABLE_AVX_INTRINSICS` changes nothing, disassembly looks exactly same

**Comment by hessfire** [comment]
oh, wait, i think i figured out

i should add `#define JM_XORSTR_DISABLE_AVX_INTRINSICS` inside of xor.h file but not inside my main file

**Comment by hessfire** [comment]
closing as completed

**Comment by JustasMasiulis** [comment]
> oh, wait, i think i figured out
> 
> i should add `#define JM_XORSTR_DISABLE_AVX_INTRINSICS` inside of xor.h file but not inside my main file

it can be in your main file as long as it's placed before the #include or alternatively you can add it in you compiler settings
