### ISSUE TITLE
ida jm xorstr decrypt plugin

### ISSUE THREAD

**Issue by Xed0sS** [JustasMasiulis/xorstr#62]
Do you plan to fix [this](https://github.com/yubie-re/ida-jm-xorstr-decrypt-plugin)?

**Comment by 0xGREG** [comment]
The project is open source, you can create your own private fork and make modifications so the linked project doesn't work on it.

**Comment by JustasMasiulis** [comment]
I don't really plan to do anything about this unless I get quite a few people complaining. The tool is rather brittle and making any modification to the ordering of the operations would probably break it.

**Comment by Xed0sS** [comment]
It's really sucks, anyway I've fixed that decryption plugin.
